-- This query calculates the total revenue generated by each author's book sales
-- It joins the Books and OrderDetails tables to combine book prices with order quantities
-- The SUM function multiplies price by quantity to get revenue per order, then sums for each author
-- GROUP BY aggregates the revenue by author
-- Results are ordered by total revenue in descending order to show highest-earning authors first
SELECT 
    b.author, 
    SUM(b.price * od.quantity) as total_revenue  -- Calculate total money earned
FROM 
    Books b
    JOIN OrderDetails od ON b.book_id = od.book_id  -- Connect books to orders
GROUP BY 
    b.author  -- Combine results for each author
ORDER BY 
    total_revenue DESC;  -- Highest earning authors first
